---
- name: Ensure basic utilities are installed
  become: false
  ansible.builtin.package:
    name:
      - git
      - curl
      - wget
    state: present

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'

- name: Ensure .local/bin directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.local/bin"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'
